version: '3'

services:
  ui:
    build: qlack-base-application-ui
    image: qlack/qba-ui:3.2.1
    container_name: qba-ui
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - "6565:80"
  server:
    build: qlack-base-application-server
    image: qlack/qba-server:3.2.1
    container_name: qba-server
    restart: unless-stopped
    environment:
      - server.port=46000
