# spring properties
spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    name: qDS
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    initialization-mode: always
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      maximum-pool-size: 100
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    open-in-view: false
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

server:
  servlet:
    context-path: /api
  error:
    include-stacktrace: never

qlack:
  util:
    jwt:
      issuer: qlack_demo
      validity: 1440
