# spring properties
spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    name: qDS
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=value;DATABASE_TO_LOWER=true;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    initialization-mode: always
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      maximum-pool-size: 100
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    open-in-view: false
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

server:
  servlet:
    context-path: /api
    session:
      cookie:
        same-site: Lax
  error:
    include-stacktrace: never

qlack:
  util:
    jwt:
      issuer: qlack_demo
      validity: 1440
    csrf:
      cookie-name: COOKIE-TOKEN # the name of the cookie
      cookie-timer: 60 # per seconds, the timer for keep old cookies alive for multiple requests
      cookie-cache-clean-timer: 0 * * ? * * # the scheduler where we clean cache from non-valid cookies
      login-path: '/users/auth'
      logout-path: '/users/logout'

      # 0 * * ? * * 	Every minute
      # 0 0 * ? * * 	Every hour

logging:
  level:
    root: error
    com.eurodyn.qlack: info
    org.springframework.security: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: '*'





