# spring properties
spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    name: qDS
    url: jdbc:mysql://localhost:3306/sample?autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: jijikos
    initialization-mode: always
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      maximum-pool-size: 100
      register-mbeans: true
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
fs:
    fs-root: "C:\\Users\\rgkol\\qlack-base-fs"